cmake_minimum_required(VERSION 3.5)
project(CPDFinal)
add_library(hashTableLib src/hash_table.cpp)
add_library(trieLib src/trie.cpp)
target_include_directories(hashTableLib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_include_directories(trieLib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
add_executable(cpdFinalApp src/main.cpp)
target_link_libraries(cpdFinalApp hashTableLib)
target_link_libraries(cpdFinalApp trieLib)